### ISSUE TITLE
能支持文件夹上传吗?

### ISSUE THREAD

**Issue by daofeng2015** [K265/aliyundrive-go#8]

**Comment by K265** [comment]
Hi, @daofeng2015 

This is already done by <https://github.com/K265/rclone/tree/aliyundrive-backend>.
Add *--tpslimit* if you meet 429 error.

**Comment by daofeng2015** [comment]
> Hi, @daofeng2015
> 
> This is already done by https://github.com/K265/rclone/tree/aliyundrive-backend.
> Add _--tpslimit_ if you meet 429 error.
目前不能指定上传到那个文件夹吗?还有我直接上传文件夹,就只能把里面所有文件都上传到root

**Comment by K265** [comment]
> > Hi, @daofeng2015
> > This is already done by https://github.com/K265/rclone/tree/aliyundrive-backend.
> > Add _--tpslimit_ if you meet 429 error.
> > 目前不能指定上传到那个文件夹吗?还有我直接上传文件夹,就只能把里面所有文件都上传到root

assume you have following files to upload:

```sh
$ cd backup
$ tree
.
├── a
│   └── a.txt
└── b
    ├── b.txt
    └── c
        └── c.txt
```

run following command:

```sh
$ cd backup
$ rclone copy . ali: -P --tpslimit 10
```

then *rclone* will upload all folders and files for you to the root of your aliyun drive.
Change *ali:* to *ali:/somewhere* if you want to upload to different folder : )

**Comment by daofeng2015** [comment]
> > > Hi, @daofeng2015
> > > This is already done by https://github.com/K265/rclone/tree/aliyundrive-backend.
> > > Add _--tpslimit_ if you meet 429 error.
> > > 目前不能指定上传到那个文件夹吗?还有我直接上传文件夹,就只能把里面所有文件都上传到root
> 
> assume you have following files to upload:
> 
> ```shell
> $ cd backup
> $ tree
> .
> ├── a
> │   └── a.txt
> └── b
>     ├── b.txt
>     └── c
>         └── c.txt
> ```
> 
> run following command:
> 
> ```shell
> $ cd backup
> $ rclone copy . ali: -P --tpslimit 10
> ```
> 
> then _rclone_ will upload all folders and files for you to the root of your aliyun drive.
> Change _ali:_ to _ali:/somewhere_ if you want to upload to a different folder : )
```
./rclone --config rclone.conf -P copy 2021-09-11 ali: --tpslimit 10
2021-09-12 19:18:01 ERROR : 夏小芫-2021-09-11-part-001.mp4: corrupted on transfer: sizes differ 7272241683 vs 3221225472
2021-09-12 19:19:48 ERROR : 夏小芫-2021-09-11-part-002.mp4: corrupted on transfer: sizes differ 7271724488 vs 3221225472
2021-09-12 19:24:09 ERROR : 夏小芫-2021-09-11-part-003.mp4: corrupted on transfer: sizes differ 7272134741 vs 3221225472
2021-09-12 19:24:53 ERROR : 夏小芫-2021-09-11-part-000.mp4: corrupted on transfer: sizes differ 7272337071 vs 3221225472
2021-09-12 19:24:53 ERROR : Attempt 1/3 failed with 4 errors and: corrupted on transfer: sizes differ 7272337071 vs 3222
```
为什么多文件上传老是在这个地方失败,而且每次重试都是这样

**Comment by K265** [comment]
@daofeng2015 

Please check your aliyun drive to see if *夏小芫-2021-09-11-part-001.mp4* exists.
If it exists, compare it with your local file.
If files mismatch, try run *rclone* again with `-vvv`. 
You should see that the remote file is removed before the actual upload.

Also, you may try to reduce the file size to see if it helps.
